### ISSUE TITLE
Data Tables Boostrap

### ISSUE THREAD

**Issue by bestickley** [toert/isolated-bootstrap#3]
Hello, 

First of all, thank you for such a simple solution to isolating bootstrap. I've used this in other projects with success. However, now I'm now using dataTables.boostrap4.min.css and I've tried to apply your bootstrap isolation code and it's not working. Any ideas for work-arounds? 

Here is the head of my html to give you an idea of what I'm trying to do. When I use the bootstrap div, it doesn't isolate (I'm guessing because I have the dataTables version of bootstrap too).

`<head>
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/iso_bootstrap.min.css">
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/fontawesome-all.min.css">       
    <link rel="stylesheet" href="../SiteAssets/JONtoFIP/custom.css">
</head>`

**Comment by toert** [comment]
@bestickley Thanks a lot for the issue opening.
However you didn't send the head of your HTML page. Can you try to resend it?

**Comment by bestickley** [comment]
Whoops! Tried to use the input code option but it didn't work for some reason. 

Here you go:

<head>
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/bootstrap.min.css">
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/fontawesome-all.min.css">       
    <link rel="stylesheet" href="../SiteAssets/JONtoFIP/custom.css">
</head>

**Comment by bestickley** [comment]
<head>
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/bootstrap.min.css">
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="../SiteAssets/WebDevLibs/fontawesome-all.min.css">       
    <link rel="stylesheet" href="../SiteAssets/JONtoFIP/custom.css">
</head>

**Comment by bestickley** [comment]
![image](https://user-images.githubusercontent.com/35735118/37095184-340b37b8-21e3-11e8-9d3a-455f695338d3.png)

**Comment by bestickley** [comment]
I've resorted to not using datatables bootstrap file and I'm just using your file (4.0.0) now. Are you planning on updating the 4.0.0 beta anytime? I saw a couple of things missing. For example, I tried to use text-center on my table but it was overidden by the table td with left aligned text. Also, table-secondary wasn't included so I've been adding the functionality I need as I go.

**Comment by toert** [comment]
Ok, I will soon update to Bootstrap 4 release version
