### ISSUE TITLE
Glyphicons returning 404

### ISSUE THREAD

**Issue by aamnakhan** [toert/isolated-bootstrap#4]
Hi! Thank you so much for this solution. Needed to isolate the Bootstrap CSS to a single input field and this worked like a charm.

However the Glyphicons are not loading. I get a 404
![Screen Shot 2019-04-17 at 3 57 01 PM](https://user-images.githubusercontent.com/7508121/56281142-7b32f000-6129-11e9-80fd-0351930be76b.png)

https://github.com/toert/Isolated-Bootstrap/blob/d333ab6934612dc348d700220e5a0e7b54ca9def/versions/3.3.7/iso_bootstrap3.3.7.css#L287

Am I doing something wrong? Please guide.

**Comment by aamnakhan** [comment]
Tried creating a PR for adding the fonts. Unable to create one.

**Comment by toert** [comment]
Thank you for your contribution. I have merged your changes to a master branch. Also praying to God it works :D
