### ISSUE TITLE
How to achieve it by myself?

### ISSUE THREAD

**Issue by ceerqingting** [toert/isolated-bootstrap#6]

**Comment by toert** [comment]
@ceerqingting hi, can you provide a more detailed description of your problem?

**Comment by toert** [comment]
If you trying to isolate another CSS however it seems tricky for you: take a look at Sass CSS compiler. It's easy to use!

**Comment by ceerqingting** [comment]
> If you trying to isolate another CSS however it seems tricky for you: take a look at Sass CSS compiler. It's easy to use!

thanks, it can achieve in this way:

change the `bootstrap.scss`  file

 .bootstrap-styles {
  @import "functions";
  @import "variables";
  ....
}

recompile the css file
